Add basic login/passwd auth
ALLATRA-IT/cloudobs pull request #103
Opened 2023-05-27 07:15 UTC by jurilents

2023-06-03 07:59 UTC, amukhsimov commented
Мне кажется было бы хорошо выстроить процесс (архитектуру) следующим образом:

1. У класса Skipper должен быть подкласс что-то вроде SecurityWorker.

1.1. В SecurityWorker нужны следующие методы:
   - `authorize(self, sid, login, password)` -> True/False - возвращает, авторизован правильные ли креды (в качестве пароля надо подумать, возможно с фронта лучше передавать хеш пароля, можно просто md5 взять). Сохраняет внутри себя состояние авторизации плюс привязывает это к сессии.
   
   - `logout(self, sid)` - лог аут, удаляется ID сессии
   
   - `sync_from_sheets()` - этот метод вызывается каждые 30-60 секунд из Skipper.BGWorker(), и если уже была задана гугл табличка set_sheets(), то пуллит новых юзеров, если таковые есть. Причем он сразу после пулла заменяет в гугл табличке пароли на хэши. Стоит отметить. Вся ролевая модель хранится в этом классе в памяти, и полностью обновляется при вызове sync_from_sheets(), надо прописать RLock() чтобы в параллельных потоках все было ок, т.к. sync_from_sheets() будет вызываться в отдельном потоке, а check() в другом потоке. Мастер-пароль (администратора) должен тоже присутствовать здесь в списке пользователей (он заносится туда при инициализации, еще до того, как устанавливается google sheet).
   Также потом на подумать - что делать если юзер удалился из гугл таблички, а сессия еще действует. Этот момент пока можно опустить за тем, что такого скорее всего не будет.
   
   - `set_sheets(sheet_url, sheet_name)` - при вызове этого метода, если все ок, внутри этого же метода автоматом вызывается `self.sync_from_sheets()`. Этот метод вызывается при вызове команды `command == "pull config"` (см. метод `Command._exec()`
   
   - `get_sid_role(self, sid) -> Permission` - этот метод возвращает информацию по ID сессии. Возвращает информацию по правам (нужно подумать что он возвращает, отлично было бы сделать класс-модель Permission, и в этом объекте класса Permission уже возвращать языки и права к языкам. Если языки все, то можно отметить код языка `"*"` как в других местах).
   

2. В момент когда идет инициализация -> передается мастер-пароль (логин пароль). И при вызове команды `pull config` инициализируется объект гугл таблички для кредов. Но сам класс SecurityWorker работает и без инициализации гугл таблички кредов, просто он чекает только мастер пароль (администратора). То есть инициализировать сервер может только администратор.

3. При подключении пользователя в методе `Skipper._on_connect()` - вызывается сначала метод `self.security_worker.authorize(login, password)` если он возвращает True - то все ок, иначе возвращаем ошибку авторизации.

4. Также нужно прописать вызов метода `self.security_worker.logout(sid)` в методе `Skipper._on_disconnect()`

5. Ну и ... нужно перед отправкой ивента on_registry_change перед отправкой реестра убирать все ненужное, но там при отправке момент есть непонятный, там сейчас стоит broadcast=True - то есть шлется всем пользователям, получается, что нужно слать каждому отдельно)

6. Также перед выполнением команды нужно проверять есть ли у пользователя права. Например удалять миньены `delete minions`, или `unlock infrastructure` может сделать только администратор. Было бы хорошо как-то интегрировать проверку прав в класс Permission, но это надо продумать

2023-06-08 15:23 UTC, jurilents commented
Обновил. Правда, вместо класса `Permission`, сделал класс `User`. Мне кажется так будет чуть логичнее, а `permissions` – это поле в классе `User`. Ещё нужно будет, чтобы Акмаль дописал в комманды, которые должны быть доступны только админу проверку `user.ensure_is_admin()`.

2023-06-08 18:22 UTC, amukhsimov requested changes

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +            if user is None or not user.passwd_hash and session.ip not in no_auth_ips:
Вот тут хорошо бы явно указать приоритет `or` и `and`, потому что это путает иногда, например `if (user is None or not user.passwd_hash) and session.ip not in ...`

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
>              # if the server is sleeping - only allow the following commands
Вот здесь, до `if self.skipper.registry.server_status == State.sleeping:`

Нужно сделать чек прав пользователя.
 - Админа и active_vmix_player пропускаем дальше
 - А для пользователя разрешены следующие команды
   - `get info`
   - `set stream settings`
   - `set teamspeak offset`
   - `set teamspeak volume`
   - `set source volume`
   - `set vmix speaker background volume`
   - `set sidechain settings`
   - `set transition settings`
   - `start streaming`
   - `stop streaming`
   - `refresh source`
   - `get logs`
   
Необходимо проверку на эти команды засунуть не сюда, а в другое более удобное место, например в класс User, или в SecurityWorker, или куда-то еще, чтобы было удобно и интуитивно понятно. Это для того, что если вдруг добавим еще команды, было бы проще вносить их в список user-shared команд.

Также при проверке команд нужно проверить правильный ли язык выбрал пользователь (в функции `_check_caller` параметр `lang`. `lang` должен быть в массиве языков в `permissions`)

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +                    command["lang"] = user.langs()[0]  # TODO: not sure about getting by index[0] here
Можно пока оставить индекс 0. Но следующей задачей надо будет подумать, как сделать так, чтобы `command["lang"]` содержал более одного языка.

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +                    user.ensure_is_admin()
Это можно в принципе убрать отсюда, так как оно будет проверяться в `self._check_caller()`

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +                    user.ensure_is_admin()
Это тоже можно убрать

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +                    user.ensure_lang_access(lang)
И это тоже

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +                        session.ensure_lang_access(lang)
И это

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +            user = self.security.authorize(sid, login, password)
`authorize` жеж возвращает `bool`, не?

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +            user = self.security.authorize(sid, login, password)
Можно тогда `authorized_status = self.security...`
```
if authorized_status:
  ...
else:
  ...
```

2023-06-08 18:22 UTC, amukhsimov commented on server/skipper.py
> +        if sid in self._sessions.keys():
Тут можно просто `if sid in self._sessions:`
Без `self._sessions.keys()`

2023-06-11 06:04 UTC, amukhsimov requested changes

2023-06-11 06:04 UTC, amukhsimov commented on server/skipper.py
> +        def copy_registry_for_user(self, user: User, masked=True) -> dict:
Надо бы еще такую же обработку registry добавить в функцию `EventSender.send_registry_change()`. Предлагаю сделать функцию в `SecurityWorker` назвать ее что-то вроде `adjust_registry_for(self, sid, registry)`
И в ней уже грохать ненужные поля в `registry`.
Эту же функцию вызывать в функции `EventSender.send_registry_change` и тут в `copy_registry_for_user` тоже.

Также в `EventSender.send_registry_change()` нужно проходиться по всем юзерам, вызывая `adjust_registry_for(user_sid, registry_changes)` и отправляя event уже конкретному пользователю

2023-06-11 10:00 UTC, merged