Refactoring/logging events
ALLATRA-IT/cloudobs pull request #98
Opened 2023-03-05 02:43 UTC by jurilents

Основное:
- Добавил класс `EventSender`. Теперь вся логика по отправке событий через сокеты будет в одном месте.
- Соответственно в `Registry` поменял прямой вызов ивента на вызов посредством этого класса
- Также добавил сюда метод на отправку любых логов

Отправка логов происходит на следующие события:
- `command_started` перед выполнением ПРОДОЛЖИТЕЛЬНОЙ команды (пока НЕ ЮЗАЕТСЯ, надо будет решить, на какие из команд стоит его повесить, какие предположительно будут самые длительные)
- `command_completed` после выполнения любой команды
- `skipper_error` если что-то пошло не так при выполнении команды (потом можно будет добавить его на любые ошибки во всех местах на стороне шкипера)
- `minion_error` если что-то не так на миньоне (сейчас если не получилось приконнектиться к миньону)
- `minion_setup_error` если что-то не так при инициализации миньонов (не уверен, на сколько это надо/правильно)

2023-03-05 06:57 UTC, amukhsimov requested changes

2023-03-05 06:57 UTC, amukhsimov commented on models/models.py
> +    _skipper = PrivateAttr()
Я бы skipper отсюда пока убрал бы)) В прошлый раз убирал потому что это не всегда сработает.
Например, если будет `registry.infrastructure_lock = value` - то __setattr__ сработает, но если будет что-то типа `registry.timing_list.append(value)` или `registry.minion_settings["Bel"] = value` - то __setattr__ не сработает, потому что тут вызов идет `registry.__getattr__("minion_settings").__setitem__("Bel", value)`

2023-03-05 06:57 UTC, amukhsimov commented on models/models.py
> +    def __init__(self, skipper, **kwargs):
+ тоже самое

2023-03-05 06:57 UTC, amukhsimov commented on models/models.py
> +        if key in ("_lock", "_skipper", "infrastructure_lock"):
тоже

2023-03-05 06:57 UTC, amukhsimov commented on models/models.py
> +            self._skipper.event_sender.send_registry_change(self.dict())
тоже

2023-03-05 06:57 UTC, amukhsimov commented on server/skipper.py
> +                raise ConnectionError(f"{message}. Details:\n{ex}")
Тут две строки подряд ConnectionError -  надо оставить одну

2023-03-05 06:57 UTC, amukhsimov commented on server/skipper.py
> +        self.registry: Registry = Registry(self)
Тут тоже к теме о registry_change

2023-03-05 06:57 UTC, amukhsimov commented on server/skipper.py
> +            self.skipper.sio.emit("on_registry_change", data=json.dumps(registry), broadcast=True)
Тут registry в json переводить надо библиотекой orjson, она нормально может обработать даты, и формат отправки: {"registry": registry.dict()}

`orjson_dumps({"registry": self.skipper.registry.dict()})`

2023-03-05 10:54 UTC, jurilents commented on models/models.py
> +    _skipper = PrivateAttr()
Я обновил логику отправки изменений реестра. Теперь ивенты отправляются именно там, где происходят какие-то изменения. Однако все равно для этого пришлось оставить в самом реестре отправку ивентов, но теперь не на любые изменения в `__setattr__`, а только на изменения `infrastructure_lock` и `server_status`, потому что они уж слишком часто меняются и это будет не очень смотреться, если там же ещё и ивенты слать

2023-03-05 10:55 UTC, jurilents commented on server/skipper.py
> +                raise ConnectionError(f"{message}. Details:\n{ex}")
Упс, похоже при мерже веток пропустил :)

2023-03-07 13:09 UTC, amukhsimov requested changes

2023-03-07 13:09 UTC, amukhsimov commented on server/skipper.py
> +                if (a in primitive_types and a == b) or (orjson_dumps(a) == orjson_dumps(b)):
А еще, `a in primitive_types` - не сработает просто потому, что `primitive_types` - список типов, а `a` - объект

2023-03-07 13:09 UTC, amukhsimov commented on server/skipper.py
> +        self.registry = Registry(self)
Тоже

2023-03-07 13:09 UTC, amukhsimov commented on models/logging.py
> +    _lock = PrivateAttr()
Тут в принципе `PrivateAttr()` лишний, так как `LogsStorage` не является pydantic моделью, можно просто None

2023-03-07 13:46 UTC, merged